/**
* Family App API
* This is a familyapp API
*
* OpenAPI spec version: 1.0.0
* Contact: you@your-company.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.server.models

import io.swagger.server.models.ByteArray
import io.swagger.server.models.Invite
import io.swagger.server.models.ShoppingList
import io.swagger.server.models.User

/**
 * 
 * @param ID 
 * @param picture 
 * @param users 
 * @param shoppinglists 
 * @param invites 
 */
data class Family (
    val ID: java.util.UUID,
    val picture: ByteArray? = null,
    val users: kotlin.Array<User>? = null,
    val shoppinglists: kotlin.Array<ShoppingList>? = null,
    val invites: kotlin.Array<Invite>? = null
) {

}

