/**
* Family App API
* This is a familyapp API
*
* OpenAPI spec version: 1.0.0
* Contact: you@your-company.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.server.models

import io.swagger.server.models.Family
import io.swagger.server.models.User

/**
 * 
 * @param ID 
 * @param userID 
 * @param User 
 * @param familyID 
 * @param Family 
 */
data class Invite (
    val ID: java.util.UUID,
    val userID: java.util.UUID,
    val familyID: java.util.UUID,
    val User: User? = null,
    val Family: Family? = null
) {

}

