/**
* Family App API
* This is a familyapp API
*
* OpenAPI spec version: 1.0.0
* Contact: you@your-company.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.server.models

import io.swagger.server.models.ShoppingList

/**
 * 
 * @param ID 
 * @param name 
 * @param done 
 * @param shoppinglistID 
 * @param ShoppingList 
 */
data class ShoppingItem (
    val ID: java.util.UUID,
    val name: kotlin.String,
    val shoppinglistID: java.util.UUID,
    val done: kotlin.Boolean? = null,
    val ShoppingList: ShoppingList? = null
) {

}

