/**
* Family App API
* This is a familyapp API
*
* OpenAPI spec version: 1.0.0
* Contact: you@your-company.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.server.models

import io.swagger.server.models.Family
import io.swagger.server.models.ShoppingItem
import io.swagger.server.models.User

/**
 * 
 * @param ID 
 * @param name 
 * @param familyID 
 * @param Family 
 * @param users 
 * @param items 
 */
data class ShoppingList (
    val ID: java.util.UUID,
    val name: kotlin.String,
    val familyID: java.util.UUID,
    val Family: Family? = null,
    val users: kotlin.Array<User>? = null,
    val items: kotlin.Array<ShoppingItem>? = null
) {

}

